server:
  port: 8877
  compression:
    enabled: true

# ===================================================================
# Servlet Config
# ===================================================================
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  application:
    name: telegram-bot